/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.55.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.4
*/

export type { SwayAbi } from './SwayAbi';

export { SwayAbi__factory } from './factories/SwayAbi__factory';
